### ISSUE TITLE
Model

### ISSUE THREAD

**Issue by AlfinaRahmawati** [chrispmaag/flask_with_tensorflow_lite#1]
hello sir.. how did you make the model? I have succeeded in making a model but the prediction results do not match. Thank you sir

**Comment by chrispmaag** [comment]
I touched on it briefly in the first paragraph of the README. You can often use pre-trained models and add a little fine tuning to make it match the number of classes you are trying to predict for an image classification task. You might find the following links helpful: https://www.tensorflow.org/tutorials/images/transfer_learning, https://www.tensorflow.org/lite/models/trained

**Comment by AlfinaRahmawati** [comment]
Thank you sir
